project:
  type: website

website:
  site-url: https://ninjalabo.github.io/
  repo-url: https://github.com/ninjalabo/ninjalabo.github.io
  repo-actions: [edit, issue]
  page-navigation: true
  title: "NinjaLABO"
  image: "images/logo.jpg"
  favicon: "images/favicon.png"
  page-footer: 
    left: |
      Copyright 2023-2024, NinjaLABO
    center: |
      **Get support**  

      - For pricing and sales inquiries <sales@ninjalabo.ai> 
      - Ask tech questions <help@ninjalabo.ai> 

    right: 
      - text: "Helsinki, Finland" 
      - icon: twitter
        href: https://twitter.com/ninjalabo
        aria-label: NinjaLABO Twitter
      - icon: linkedin
        href: https://www.linkedin.com/company/ninjalabo/
        aria-label: NinjaLABO LinkedIn
      - icon: github
        href: https://github.com/ninjalabo/ninjalabo.github.io
        aria-label: NinjaLABO GitHub

  twitter-card: true
  navbar:
    background: dark
    logo: "images/logo.jpg"
    logo-alt: "NinjaLABO log."
    title: false
    search: true
    left:
      - href: getstarted.qmd
        text: "Get Started"
      - href: pricing.qmd
        text: "Pricing"
      - href: blog.qmd
        text: "Blog"
      - href: news.qmd
        text: "News"
      - href: performance.ipynb
        text: "Performance"
    right:
      - icon: twitter
        href: https://twitter.com/ninjalabo
      - icon: linkedin
        href: https://www.linkedin.com/company/ninjalabo/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/ninjalabo/ninjalabo.github.io
          - text: Report a Bug
            href: https://github.com/ninjalabo/ninjalabo.github.io/issues

  sidebar:
    - title: "Get Started"
      style: "docked"
      search: true
      contents: 
        - about.qmd
        - getstarted.qmd
        - section: "Tutorials"
          contents: 
           - tutorials/runwalkthrough.qmd
        - section: "Documentation"
          contents:
            - docs/architecture.qmd
        # navigation items
    - title: "Performance"
      style: "docked"
      search: true
      contents:
        - performance.ipynb

format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css
    toc: true
