project:
  type: website

website:
  site-url: https://ninjalabo.github.io/
  repo-url: https://github.com/ninjalabo/ninjalabo.github.io
  repo-actions: [edit, issue]
  page-navigation: true
  title: "NinjaLABO"
  image: "images/logo.png"
  favicon: "images/favicon.png"
  page-footer: 
    left: |
      Copyright 2023-2024, NinjaLABO
    center: |
      **Get support**  

      - For pricing and sales inquiries <sales@ninjalabo.ai> 
      - Ask tech questions <help@ninjalabo.ai> 

    right: 
      - text: "Helsinki, Finland" 
      - icon: twitter
        href: https://twitter.com/ninjalabo
        aria-label: NinjaLABO Twitter
      - icon: github
        href: https://github.com/ninjalabo/ninjalabo.github.io
        aria-label: NinjaLABO GitHub

  twitter-card: true
  navbar:
    background: dark
    logo: "images/favicon.png"
    logo-alt: "NinjaLABO log."
    title: false
    search: true
    left:
      - href: index.qmd
        text: "Overview"
      - href: tutorial.qmd
        text: "Tutorial"
      - href: pricing.qmd
        text: "Pricing"
      - href: blog.qmd
        text: "Blog"
    right:
      - icon: twitter
        href: https://twitter.com/ninjalabo
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/ninjalabo/ninjalabo.github.io
          - text: Report a Bug
            href: https://github.com/ninjalabo/ninjalabo.github.io/issues

  sidebar:
    - title: "Tutorial"
      style: "docked"
      search: true
      contents: 
        - about.qmd
        - tutorial.qmd
        # navigation items
    - title: "Blog"
      style: "docked"
      search: true
      contents: 
        - blog.qmd
        # navigation items

format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css
    toc: true
