on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Install python and jupyter to execute performance.ipynb to keep it up-to-date
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Jupyter nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas matplotlib plotly kaleido

      - name: Execute Jupyter Notebook
        run: |
          # Execute hello.ipynb
          jupyter nbconvert --execute performance.ipynb --to notebook --output performance.ipynb

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
