name: Update performance comparison images

on:
  push:
    branches:
      - main
    paths:
      - performance.ipynb
      - benchmark.csv
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install python and jupyter to execute performance.ipynb to run notebook
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter pandas matplotlib plotly kaleido

    - name: Run Jupyter notebook
      run: |
        jupyter nbconvert --to notebook --execute performance.ipynb

    - name: Commit and push images
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        if git status images/ --porcelain | grep images; then
          git add images/
          git commit -m "Update generated images from notebook"
          git push origin main
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
